### ISSUE TITLE
NotADirectoryError: [WinError 267]

### ISSUE THREAD

**Issue by x7n3m6ee** [safreita1/TIGER#3]
I tried to attack(), but I got this error:

---------------------------------------------------------------------------
NotADirectoryError                        Traceback (most recent call last)
<ipython-input-119-3d0bb12dc3eb> in <module>
----> 1 a=Attack(UG)

~\anaconda3\lib\site-packages\graph_tiger\attacks.py in __init__(self, graph, runs, steps, attack, defense, k_d, **kwargs)
    450 
    451         self.save_dir = os.path.join(os.getcwd(), 'plots', self.get_plot_title(steps))
--> 452         os.makedirs(self.save_dir, exist_ok=True)
    453 
    454         self.attacked = []

~\anaconda3\lib\os.py in makedirs(name, mode, exist_ok)
    221             return
    222     try:
--> 223         mkdir(name, mode)
    224     except OSError:
    225         # Cannot rely on checking for EEXIST, since the operating system

NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\29369\\plots\\Attack:step=50,attack=id_node,k_d=0,defense=None

_________________________________________________________________________________________________

how can I fix this? Really need your help

**Comment by safreita1** [comment]
Hi, sorry for taking so long to respond. Since the library was developed in Linux it looks like it was a bug when switching to Windows. It turns out that the ":" character is invalid in Windows directories, causing the error to occur. I just fixed the bug and will push an update to the repo soon.
